//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MipsToBinary/MipsAsm.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MipsAsmParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
// [System.CLSCompliant(false)]
public interface IMipsAsmVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] MipsAsmParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.iden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIden([NotNull] MipsAsmParser.IdenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] MipsAsmParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReg([NotNull] MipsAsmParser.RegContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.usigned_imm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsigned_imm([NotNull] MipsAsmParser.Usigned_immContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.signed_imm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_imm([NotNull] MipsAsmParser.Signed_immContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat([NotNull] MipsAsmParser.StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_add([NotNull] MipsAsmParser.Op_addContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_addu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_addu([NotNull] MipsAsmParser.Op_adduContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sub([NotNull] MipsAsmParser.Op_subContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_and([NotNull] MipsAsmParser.Op_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_or([NotNull] MipsAsmParser.Op_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_nor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_nor([NotNull] MipsAsmParser.Op_norContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_xor([NotNull] MipsAsmParser.Op_xorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_nand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_nand([NotNull] MipsAsmParser.Op_nandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_slt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_slt([NotNull] MipsAsmParser.Op_sltContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sltu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sltu([NotNull] MipsAsmParser.Op_sltuContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sll([NotNull] MipsAsmParser.Op_sllContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_srl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_srl([NotNull] MipsAsmParser.Op_srlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sra"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sra([NotNull] MipsAsmParser.Op_sraContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_jr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_jr([NotNull] MipsAsmParser.Op_jrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.instr_r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr_r([NotNull] MipsAsmParser.Instr_rContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_addi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_addi([NotNull] MipsAsmParser.Op_addiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_addiu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_addiu([NotNull] MipsAsmParser.Op_addiuContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_lw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_lw([NotNull] MipsAsmParser.Op_lwContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_lh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_lh([NotNull] MipsAsmParser.Op_lhContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_lhu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_lhu([NotNull] MipsAsmParser.Op_lhuContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_lb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_lb([NotNull] MipsAsmParser.Op_lbContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_lbu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_lbu([NotNull] MipsAsmParser.Op_lbuContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sw([NotNull] MipsAsmParser.Op_swContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sh([NotNull] MipsAsmParser.Op_shContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_sb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_sb([NotNull] MipsAsmParser.Op_sbContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_lui"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_lui([NotNull] MipsAsmParser.Op_luiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_andi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_andi([NotNull] MipsAsmParser.Op_andiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_ori"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_ori([NotNull] MipsAsmParser.Op_oriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_nori"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_nori([NotNull] MipsAsmParser.Op_noriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_slti"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_slti([NotNull] MipsAsmParser.Op_sltiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_beq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_beq([NotNull] MipsAsmParser.Op_beqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_bne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_bne([NotNull] MipsAsmParser.Op_bneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_bgtz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_bgtz([NotNull] MipsAsmParser.Op_bgtzContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.instr_i"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr_i([NotNull] MipsAsmParser.Instr_iContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_j([NotNull] MipsAsmParser.Op_jContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_jal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_jal([NotNull] MipsAsmParser.Op_jalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.instr_j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr_j([NotNull] MipsAsmParser.Instr_jContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_halt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_halt([NotNull] MipsAsmParser.Op_haltContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr([NotNull] MipsAsmParser.InstrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.instr_pseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr_pseudo([NotNull] MipsAsmParser.Instr_pseudoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_bgt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_bgt([NotNull] MipsAsmParser.Op_bgtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MipsAsmParser.op_move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_move([NotNull] MipsAsmParser.Op_moveContext context);
}
