//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MipsToBinary/MipsAsm.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MipsAsmParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
// [System.CLSCompliant(false)]
public interface IMipsAsmListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] MipsAsmParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] MipsAsmParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.iden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIden([NotNull] MipsAsmParser.IdenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.iden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIden([NotNull] MipsAsmParser.IdenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] MipsAsmParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] MipsAsmParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReg([NotNull] MipsAsmParser.RegContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReg([NotNull] MipsAsmParser.RegContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.usigned_imm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsigned_imm([NotNull] MipsAsmParser.Usigned_immContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.usigned_imm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsigned_imm([NotNull] MipsAsmParser.Usigned_immContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.signed_imm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_imm([NotNull] MipsAsmParser.Signed_immContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.signed_imm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_imm([NotNull] MipsAsmParser.Signed_immContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] MipsAsmParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] MipsAsmParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_add([NotNull] MipsAsmParser.Op_addContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_add([NotNull] MipsAsmParser.Op_addContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_addu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_addu([NotNull] MipsAsmParser.Op_adduContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_addu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_addu([NotNull] MipsAsmParser.Op_adduContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sub([NotNull] MipsAsmParser.Op_subContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sub([NotNull] MipsAsmParser.Op_subContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_and([NotNull] MipsAsmParser.Op_andContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_and([NotNull] MipsAsmParser.Op_andContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_or([NotNull] MipsAsmParser.Op_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_or([NotNull] MipsAsmParser.Op_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_nor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_nor([NotNull] MipsAsmParser.Op_norContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_nor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_nor([NotNull] MipsAsmParser.Op_norContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_xor([NotNull] MipsAsmParser.Op_xorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_xor([NotNull] MipsAsmParser.Op_xorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_nand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_nand([NotNull] MipsAsmParser.Op_nandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_nand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_nand([NotNull] MipsAsmParser.Op_nandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_slt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_slt([NotNull] MipsAsmParser.Op_sltContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_slt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_slt([NotNull] MipsAsmParser.Op_sltContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sltu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sltu([NotNull] MipsAsmParser.Op_sltuContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sltu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sltu([NotNull] MipsAsmParser.Op_sltuContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sll([NotNull] MipsAsmParser.Op_sllContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sll([NotNull] MipsAsmParser.Op_sllContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_srl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_srl([NotNull] MipsAsmParser.Op_srlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_srl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_srl([NotNull] MipsAsmParser.Op_srlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sra"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sra([NotNull] MipsAsmParser.Op_sraContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sra"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sra([NotNull] MipsAsmParser.Op_sraContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_jr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_jr([NotNull] MipsAsmParser.Op_jrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_jr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_jr([NotNull] MipsAsmParser.Op_jrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_r([NotNull] MipsAsmParser.Instr_rContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_r([NotNull] MipsAsmParser.Instr_rContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_addi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_addi([NotNull] MipsAsmParser.Op_addiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_addi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_addi([NotNull] MipsAsmParser.Op_addiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_addiu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_addiu([NotNull] MipsAsmParser.Op_addiuContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_addiu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_addiu([NotNull] MipsAsmParser.Op_addiuContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lw([NotNull] MipsAsmParser.Op_lwContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lw([NotNull] MipsAsmParser.Op_lwContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lh([NotNull] MipsAsmParser.Op_lhContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lh([NotNull] MipsAsmParser.Op_lhContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lhu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lhu([NotNull] MipsAsmParser.Op_lhuContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lhu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lhu([NotNull] MipsAsmParser.Op_lhuContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lb([NotNull] MipsAsmParser.Op_lbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lb([NotNull] MipsAsmParser.Op_lbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lbu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lbu([NotNull] MipsAsmParser.Op_lbuContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lbu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lbu([NotNull] MipsAsmParser.Op_lbuContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sw([NotNull] MipsAsmParser.Op_swContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sw([NotNull] MipsAsmParser.Op_swContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sh([NotNull] MipsAsmParser.Op_shContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sh([NotNull] MipsAsmParser.Op_shContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_sb([NotNull] MipsAsmParser.Op_sbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_sb([NotNull] MipsAsmParser.Op_sbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lui"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lui([NotNull] MipsAsmParser.Op_luiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lui"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lui([NotNull] MipsAsmParser.Op_luiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_andi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_andi([NotNull] MipsAsmParser.Op_andiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_andi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_andi([NotNull] MipsAsmParser.Op_andiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_ori"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_ori([NotNull] MipsAsmParser.Op_oriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_ori"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_ori([NotNull] MipsAsmParser.Op_oriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_nori"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_nori([NotNull] MipsAsmParser.Op_noriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_nori"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_nori([NotNull] MipsAsmParser.Op_noriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_slti"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_slti([NotNull] MipsAsmParser.Op_sltiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_slti"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_slti([NotNull] MipsAsmParser.Op_sltiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_beq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_beq([NotNull] MipsAsmParser.Op_beqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_beq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_beq([NotNull] MipsAsmParser.Op_beqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_bne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_bne([NotNull] MipsAsmParser.Op_bneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_bne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_bne([NotNull] MipsAsmParser.Op_bneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_bgtz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_bgtz([NotNull] MipsAsmParser.Op_bgtzContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_bgtz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_bgtz([NotNull] MipsAsmParser.Op_bgtzContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_i"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_i([NotNull] MipsAsmParser.Instr_iContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_i"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_i([NotNull] MipsAsmParser.Instr_iContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_j([NotNull] MipsAsmParser.Op_jContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_j([NotNull] MipsAsmParser.Op_jContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_jal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_jal([NotNull] MipsAsmParser.Op_jalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_jal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_jal([NotNull] MipsAsmParser.Op_jalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_j([NotNull] MipsAsmParser.Instr_jContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_j"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_j([NotNull] MipsAsmParser.Instr_jContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_halt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_halt([NotNull] MipsAsmParser.Op_haltContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_halt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_halt([NotNull] MipsAsmParser.Op_haltContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr([NotNull] MipsAsmParser.InstrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr([NotNull] MipsAsmParser.InstrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_pseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_pseudo([NotNull] MipsAsmParser.Instr_pseudoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_pseudo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_pseudo([NotNull] MipsAsmParser.Instr_pseudoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_bgt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_bgt([NotNull] MipsAsmParser.Op_bgtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_bgt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_bgt([NotNull] MipsAsmParser.Op_bgtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_move([NotNull] MipsAsmParser.Op_moveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_move([NotNull] MipsAsmParser.Op_moveContext context);
}
