//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MipsToBinary/MipsAsm.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMipsAsmListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
// [System.CLSCompliant(false)]
public partial class MipsAsmBaseListener : IMipsAsmListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] MipsAsmParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] MipsAsmParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.iden"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIden([NotNull] MipsAsmParser.IdenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.iden"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIden([NotNull] MipsAsmParser.IdenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] MipsAsmParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] MipsAsmParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.reg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReg([NotNull] MipsAsmParser.RegContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.reg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReg([NotNull] MipsAsmParser.RegContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.usigned_imm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsigned_imm([NotNull] MipsAsmParser.Usigned_immContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.usigned_imm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsigned_imm([NotNull] MipsAsmParser.Usigned_immContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.signed_imm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_imm([NotNull] MipsAsmParser.Signed_immContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.signed_imm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_imm([NotNull] MipsAsmParser.Signed_immContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] MipsAsmParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] MipsAsmParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_add([NotNull] MipsAsmParser.Op_addContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_add([NotNull] MipsAsmParser.Op_addContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_addu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_addu([NotNull] MipsAsmParser.Op_adduContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_addu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_addu([NotNull] MipsAsmParser.Op_adduContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sub([NotNull] MipsAsmParser.Op_subContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sub([NotNull] MipsAsmParser.Op_subContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_and([NotNull] MipsAsmParser.Op_andContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_and([NotNull] MipsAsmParser.Op_andContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_or([NotNull] MipsAsmParser.Op_orContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_or([NotNull] MipsAsmParser.Op_orContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_nor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_nor([NotNull] MipsAsmParser.Op_norContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_nor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_nor([NotNull] MipsAsmParser.Op_norContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_xor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_xor([NotNull] MipsAsmParser.Op_xorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_xor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_xor([NotNull] MipsAsmParser.Op_xorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_nand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_nand([NotNull] MipsAsmParser.Op_nandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_nand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_nand([NotNull] MipsAsmParser.Op_nandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_slt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_slt([NotNull] MipsAsmParser.Op_sltContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_slt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_slt([NotNull] MipsAsmParser.Op_sltContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sltu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sltu([NotNull] MipsAsmParser.Op_sltuContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sltu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sltu([NotNull] MipsAsmParser.Op_sltuContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sll([NotNull] MipsAsmParser.Op_sllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sll([NotNull] MipsAsmParser.Op_sllContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_srl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_srl([NotNull] MipsAsmParser.Op_srlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_srl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_srl([NotNull] MipsAsmParser.Op_srlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sra"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sra([NotNull] MipsAsmParser.Op_sraContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sra"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sra([NotNull] MipsAsmParser.Op_sraContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_jr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_jr([NotNull] MipsAsmParser.Op_jrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_jr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_jr([NotNull] MipsAsmParser.Op_jrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr_r([NotNull] MipsAsmParser.Instr_rContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr_r([NotNull] MipsAsmParser.Instr_rContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_addi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_addi([NotNull] MipsAsmParser.Op_addiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_addi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_addi([NotNull] MipsAsmParser.Op_addiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_addiu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_addiu([NotNull] MipsAsmParser.Op_addiuContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_addiu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_addiu([NotNull] MipsAsmParser.Op_addiuContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_lw([NotNull] MipsAsmParser.Op_lwContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_lw([NotNull] MipsAsmParser.Op_lwContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_lh([NotNull] MipsAsmParser.Op_lhContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_lh([NotNull] MipsAsmParser.Op_lhContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lhu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_lhu([NotNull] MipsAsmParser.Op_lhuContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lhu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_lhu([NotNull] MipsAsmParser.Op_lhuContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_lb([NotNull] MipsAsmParser.Op_lbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_lb([NotNull] MipsAsmParser.Op_lbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lbu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_lbu([NotNull] MipsAsmParser.Op_lbuContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lbu"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_lbu([NotNull] MipsAsmParser.Op_lbuContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sw([NotNull] MipsAsmParser.Op_swContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sw"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sw([NotNull] MipsAsmParser.Op_swContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sh([NotNull] MipsAsmParser.Op_shContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sh"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sh([NotNull] MipsAsmParser.Op_shContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_sb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_sb([NotNull] MipsAsmParser.Op_sbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_sb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_sb([NotNull] MipsAsmParser.Op_sbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_lui"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_lui([NotNull] MipsAsmParser.Op_luiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_lui"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_lui([NotNull] MipsAsmParser.Op_luiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_andi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_andi([NotNull] MipsAsmParser.Op_andiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_andi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_andi([NotNull] MipsAsmParser.Op_andiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_ori"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_ori([NotNull] MipsAsmParser.Op_oriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_ori"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_ori([NotNull] MipsAsmParser.Op_oriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_nori"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_nori([NotNull] MipsAsmParser.Op_noriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_nori"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_nori([NotNull] MipsAsmParser.Op_noriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_slti"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_slti([NotNull] MipsAsmParser.Op_sltiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_slti"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_slti([NotNull] MipsAsmParser.Op_sltiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_beq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_beq([NotNull] MipsAsmParser.Op_beqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_beq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_beq([NotNull] MipsAsmParser.Op_beqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_bne"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_bne([NotNull] MipsAsmParser.Op_bneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_bne"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_bne([NotNull] MipsAsmParser.Op_bneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_bgtz"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_bgtz([NotNull] MipsAsmParser.Op_bgtzContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_bgtz"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_bgtz([NotNull] MipsAsmParser.Op_bgtzContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_i"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr_i([NotNull] MipsAsmParser.Instr_iContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_i"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr_i([NotNull] MipsAsmParser.Instr_iContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_j"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_j([NotNull] MipsAsmParser.Op_jContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_j"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_j([NotNull] MipsAsmParser.Op_jContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_jal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_jal([NotNull] MipsAsmParser.Op_jalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_jal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_jal([NotNull] MipsAsmParser.Op_jalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_j"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr_j([NotNull] MipsAsmParser.Instr_jContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_j"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr_j([NotNull] MipsAsmParser.Instr_jContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_halt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_halt([NotNull] MipsAsmParser.Op_haltContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_halt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_halt([NotNull] MipsAsmParser.Op_haltContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr([NotNull] MipsAsmParser.InstrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr([NotNull] MipsAsmParser.InstrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.instr_pseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstr_pseudo([NotNull] MipsAsmParser.Instr_pseudoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.instr_pseudo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstr_pseudo([NotNull] MipsAsmParser.Instr_pseudoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_bgt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_bgt([NotNull] MipsAsmParser.Op_bgtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_bgt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_bgt([NotNull] MipsAsmParser.Op_bgtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MipsAsmParser.op_move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_move([NotNull] MipsAsmParser.Op_moveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MipsAsmParser.op_move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_move([NotNull] MipsAsmParser.Op_moveContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
